import path from "path";
import beforeBuild from "../../common/utils/beforeBuild.js";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

beforeBuild(
  [
    path.join(__dirname, "../public/locales"),
    path.join(__dirname, "../../../public/locales"),
  ],
  path.join(__dirname, "../src/autoGeneratedTranslations.js"),
  {
    path: path.join(__dirname, "../../client/public/locales"),
    files: [
      "ChangeOwnerPanel.json",
      "EmbeddingPanel.json",
      "Files.json",
      "PeopleSelector.json",
      "PeopleTranslations.json",
      "SharingPanel.json",
      "Translations.json",
    ],
    alias: "CLIENT_PUBLIC_DIR",
  }
);
